language: node_js
node_js:
  - "stable"
env:
  global:
    - DEPLOY_HOST=sybolt.com
cache:
  directories:
    - node_modules
script: # dummy script
  - cd .
deploy:
  provider: script
  script: bash .travis/deploy.sh
  on:
    branch: travis-tests

