language: node_js
node_js:
  - "stable"
env:
  global:
    - DEPLOY_HOST=sybolt.com
cache:
  directories:
    - node_modules
script: # dummy script
  - cd .
deploy:
  provider: script
  script: chmod +x ./.travis/deploy.sh && ./.travis/deploy.sh
