language: node_js
node_js:
  - "stable"
env:
  global:
    - DEPLOY_HOST=sybolt.com
    - DEPLOY_PORT=2222
    - DEPLOY_PATH=build
cache:
  directories:
    - node_modules
script:
  # - cd .
  # - npm test
  - npm run build
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true # preserve build artifacts
  on:
    branch: travis-tests
