language: node_js
node_js:
  - "stable"
env:
  global:
    - DEPLOY_HOST=sybolt.com
    - DEPLOY_PORT=2222
# cache:
#   directories:
#     - node_modules
# script:
#   - npm test
#   - npm run build
script: # dummy script
  - cd .
deploy:
  provider: script
  script: bash .travis/deploy.sh
  skip_cleanup: true # preserve build artifacts
  on:
    branch: travis-tests

